KPI_CONTRACTS = [
  {
    "kpi_id": "total_revenue",
    "name": "Total Revenue",
    "definition": "Sum of transaction revenue across all regions and products",
    "formula": "SUM(revenue) FROM sales_transactions",
    "grain": "Daily, aggregated to period",
    "source": "ERP / Sales DB",
    "refresh": "Daily at 06:00 UTC",
    "drivers": ["Order volume", "Product mix", "Pricing", "Regional demand", "Marketing spend"],
    "thresholds": {"material_up": 5.0, "material_down": -5.0},
    "lineage": ["sales_transactions → daily_revenue → kpi_total_revenue"],
    "access": {"CEO": "full", "Sales Manager": "regional", "Analyst": "full"},
    "owner": "Finance",
  },
  {
    "kpi_id": "total_orders",
    "name": "Total Orders",
    "definition": "Count of completed orders across all channels",
    "formula": "SUM(orders) FROM sales_transactions",
    "grain": "Daily",
    "source": "ERP / Sales DB",
    "refresh": "Daily at 06:00 UTC",
    "drivers": ["Marketing campaigns", "Seasonality", "Stock availability"],
    "thresholds": {"material_up": 8.0, "material_down": -8.0},
    "lineage": ["sales_transactions → daily_orders → kpi_total_orders"],
    "access": {"CEO": "full", "Sales Manager": "regional", "Analyst": "full"},
    "owner": "Operations",
  },
  {
    "kpi_id": "aov",
    "name": "Average Order Value",
    "definition": "Revenue divided by order count",
    "formula": "SUM(revenue) / SUM(orders)",
    "grain": "Daily, aggregated to period",
    "source": "ERP / Sales DB (derived)",
    "refresh": "Daily at 06:00 UTC",
    "drivers": ["Product mix shift", "Discounting", "Upsell rate"],
    "thresholds": {"material_up": 3.0, "material_down": -3.0},
    "lineage": ["sales_transactions → derived_aov"],
    "access": {"CEO": "full", "Sales Manager": "regional", "Analyst": "full"},
    "owner": "Finance",
  },
  {
    "kpi_id": "churn_rate",
    "name": "Customer Churn Rate",
    "definition": "Percentage of customers who churned in the period",
    "formula": "SUM(churn) / COUNT(customer_id) * 100 FROM crm_customers",
    "grain": "Monthly (regional)",
    "source": "CRM System",
    "refresh": "Weekly on Monday",
    "drivers": ["Service quality", "Competitive pricing", "Delivery experience"],
    "thresholds": {"material_up": 2.0, "material_down": -2.0},
    "lineage": ["crm_customers → regional_churn → kpi_churn_rate"],
    "access": {"CEO": "full", "Sales Manager": "regional_only", "Analyst": "full"},
    "owner": "Customer Success",
  },
  {
    "kpi_id": "sentiment_score",
    "name": "Customer Sentiment Score",
    "definition": "Aggregate sentiment from product reviews (TextBlob polarity)",
    "formula": "AVG(TextBlob polarity) per product, weighted by review count",
    "grain": "Per review, aggregated weekly",
    "source": "Review Platform API",
    "refresh": "Near real-time (15 min lag)",
    "drivers": ["Delivery speed", "Product quality", "Support responsiveness"],
    "thresholds": {"material_up": 10.0, "material_down": -10.0},
    "lineage": ["customer_reviews → sentiment_analysis → kpi_sentiment"],
    "access": {"CEO": "aggregated", "Sales Manager": "product_level", "Analyst": "full"},
    "owner": "Customer Experience",
  },
  {
    "kpi_id": "new_product_revenue",
    "name": "Sparse Product Revenue",
    "definition": "Revenue from product with least historical data (newest or sparse product)",
    "formula": "SUM(revenue) WHERE product = MIN(COUNT(distinct dates))",
    "grain": "Daily (sparse: less than 30 days of history)",
    "source": "ERP / Sales DB",
    "refresh": "Daily at 06:00 UTC",
    "drivers": ["Product launch", "Inventory availability", "Market demand"],
    "thresholds": {"material_up": 15.0, "material_down": -15.0},
    "lineage": ["sales_transactions → sparse_product_filter → kpi_sparse_product"],
    "access": {"CEO": "full", "Sales Manager": "product_level", "Analyst": "full"},
    "owner": "Product Marketing",
    "sparse_history": True,
    "history_days": 14,
  },
]

DATA_SOURCES = [
  {
    "name": "ERP / Sales DB",
    "table": "sales_transactions",
    "grain": "Transaction-level (daily rollup)",
    "refresh": "Daily 06:00 UTC",
    "last_refresh": "Today 06:00 UTC",
    "coverage": "60 days",
    "quality_score": 98,
    "status": "fresh",
  },
  {
    "name": "CRM System",
    "table": "crm_customers",
    "grain": "Customer-level (regional rollup)",
    "refresh": "Weekly Monday 08:00 UTC",
    "last_refresh": "3 days ago",
    "coverage": "12 months",
    "quality_score": 92,
    "status": "fresh",
  },
  {
    "name": "Review Platform API",
    "table": "customer_reviews",
    "grain": "Per review (product rollup)",
    "refresh": "Near real-time (15 min)",
    "last_refresh": "12 min ago",
    "coverage": "90 days",
    "quality_score": 85,
    "status": "fresh",
  },
]
